/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_managed_NativeLibB */

#ifndef _Included_com_example_managed_NativeLibB
#define _Included_com_example_managed_NativeLibB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_managed_NativeLibB
 * Method:    sayHola
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_managed_NativeLibB_sayHola
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
