/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_managed_NativeLibA */

#ifndef _Included_com_example_managed_NativeLibA
#define _Included_com_example_managed_NativeLibA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_managed_NativeLibA
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_managed_NativeLibA_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
